spring.application.name=parqueadero
spring.datasource.url=jdbc:postgresql://dpg-d7l9ordckfvc73a4spc0-a.oregon-postgres.render.com/bd_pedidos_znnz
spring.datasource.username=esteban
spring.datasource.password=x9ObFOxTxRJRDfZGAyuq3Vmp1QPLnLsY
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
